Task 3: Customer Churn Prediction (Bank Customers)

Objective:

 Identify customers who are likely to leave the bank.

Dataset:

 Churn Modelling Dataset

Instructions:

●	Clean and prepare the dataset.

●	Encode categorical features such as geography and gender.

●	Train a classification model.

●	Analyze feature importance to understand what influences churn.


Skills:

●	Categorical data encoding (Label Encoding / One-Hot Encoding)

●	Supervised classification modeling

●	Understanding and interpreting feature importance

#Import Libraries

In [6]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report

# Load Dataset

In [26]:
df = pd.read_csv("/content/Bank_Customer_Churn_Dataset.csv")
df.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15600001,Santiago,677,France,Male,65,4,61222.96,2,0,0,126288.65,1
1,2,15600002,Allen,366,France,Male,31,3,126338.82,1,0,1,59679.31,0
2,3,15600003,Golden,651,Germany,Male,66,2,174534.85,3,1,0,58756.48,1
3,4,15600004,Fitzpatrick,740,Germany,Male,23,6,24179.09,3,1,0,151351.72,1
4,5,15600005,Brown,624,France,Female,23,8,73294.57,3,0,0,28248.39,0

# Clean and Prepare Dataset

In [27]:
df = df.drop(['CustomerId','RowNumber','Surname'],axis=1)

# Encoding Dataset

In [28]:
encoder = LabelEncoder()
df['Gender'] = encoder.fit_transform(df['Gender'])

df = pd.get_dummies(df,columns=["Geography"],drop_first=True, dtype=int)
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain
0,677,1,65,4,61222.96,2,0,0,126288.65,1,0,0
1,366,1,31,3,126338.82,1,0,1,59679.31,0,0,0
2,651,1,66,2,174534.85,3,1,0,58756.48,1,1,0
3,740,1,23,6,24179.09,3,1,0,151351.72,1,1,0
4,624,0,23,8,73294.57,3,0,0,28248.39,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
145,581,1,41,4,19182.75,1,1,1,124459.29,0,0,0
146,838,1,46,9,162959.36,3,1,0,192390.02,0,0,1
147,580,0,63,1,126137.25,2,0,0,147371.91,1,0,0
148,574,1,41,5,229484.20,4,1,1,142201.59,0,0,1
149,376,0,22,5,23626.49,4,1,1,150272.06,0,0,1

# Split Dataset

In [29]:
x = df.drop('Exited',axis=1)
y = df['Exited']

X_train,X_test,y_train,y_test = train_test_split(
    x,y,
    test_size=0.2,
    random_state=42
)

# Train Model

In [30]:
model = RandomForestClassifier()
model.fit(X_train,y_train)

RandomForestClassifier()

# Prediction

In [33]:
y_predict = model.predict(X_test)
y_predict

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0])

# Performance Evaluation Metrics

In [35]:
accuracy = accuracy_score(y_test,y_predict)
accuracy

print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.93      1.00      0.96        25
           1       1.00      0.60      0.75         5

    accuracy                           0.93        30
   macro avg       0.96      0.80      0.86        30
weighted avg       0.94      0.93      0.93        30